### ISSUE TITLE
Context paths seem to be more fucked the more I look

### ISSUE THREAD

**Issue by JackLClements** [Josh-G/HealthTracker#5]
Seriously, not only does register.jsp load as the default page (with no context.xml for me to change it). Plus, submitting forms to their URL pattern servlets seems to give a nice neat little 404 to boot. Would be nice if these worked, as I can't check that anything works without them.

**Comment by JackLClements** [comment]
For the time being, for the sake of having work to complete, I'm going to ignore the context paths within the project and just focus on the servlets and forms. I figure that having the structure and linking it all up later can't hurt.

**Comment by CHAZICLE** [comment]
ServletRegister handles "/" and "/portal" and "/register" pages. After registration/login is complete it currently server redirects to "/WEB-INF/dashboard.jsp" which currently doesn't exist (hance the 404) because Josh hasn't made it yet. What exactly are you trying to do?

**Comment by JackLClements** [comment]
register.jsp's main form throws a 404 when submitted, as in it cannot find ServletRegister under any of the URL patterns.

**Comment by CHAZICLE** [comment]
Did you pull the latest?

**Comment by JackLClements** [comment]
Yup

**Comment by CHAZICLE** [comment]
oh wait, submitting a registration form is currently SUPPOSED to throw a 404 because Josh is currently working on dashboard.jsp and it will be uploaded soon. Has something else broken?

**Comment by JackLClements** [comment]
does this apply for all forms? Either way, my problem was basically just forms accessing servlets, so I guess not.

**Comment by CHAZICLE** [comment]
It should only occur when you are logged in (including after registering) and try to load "/" "/portal" or "/register" which all map to ServletRegister. Which form is broken and what is the action="" set to?

**Comment by JackLClements** [comment]
Form in register.jsp, action="register" although I've tried the other variations. I could just be getting the path wrong, but I dunno.

**Comment by CHAZICLE** [comment]
The registration, login and logout systems are all completly done (except logged in users get a blank/404 page). Were you working on some other thing that broke?

**Comment by JackLClements** [comment]
No, trying to test the registration form and its link to the servlet and a HTTP Status 404 - /register is being thrown. Unless I'm working on old code or something. I have pulled the latest version.

**Comment by CHAZICLE** [comment]
ok, josh's commit should have fixed that. I just made it throw you on a page that doens't exist when you complete it sucessfully. That's fine.

**Comment by Josh-G** [comment]
Hello, please join us on softeng1 on https://crypto.cat

**Comment by Josh-G** [comment]
^ That's for @JackLClements and @Domryuken
